/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type CarouselSection = {
  _type: 'carouselSection';
  title?: string;
  images: Array<
    {
      _key: string;
    } & ResponsiveImage
  >;
  showCtaCard?: boolean;
  ctaText?: string;
  instagramUrl?: string;
  ctaPosition?: number;
};

export type BlockContentSection = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
      _key: string;
    }
>;

export type ImageSection = {
  _type: 'imageSection';
  title: string;
  body: BlockContentSection;
  image: ResponsiveImage;
  layout: 'left' | 'right';
  fullWidth?: boolean;
};

export type ResponsiveImage = {
  _type: 'responsiveImage';
  image: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  aspectRatio: '3/4' | '9/16' | '1/1' | '4/3' | '3/2' | '13/5';
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  metadata?: {
    metaTitle?: string;
    metaDescription?: string;
    keywords?: Array<string>;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
    noIndex?: boolean;
  };
  sections: Array<
    | ({
        _key: string;
      } & ImageSection)
    | ({
        _key: string;
      } & CarouselSection)
  >;
};

export type Settings = {
  _id: string;
  _type: 'settings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  url?: string;
  phone?: string;
  mail?: string;
  address?: string;
  footerImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  nip?: string;
  bdo?: string;
  social?: Array<{
    media?: 'Twitter' | 'Facebook' | 'Instagram' | 'Linkedin' | 'Youtube';
    url?: string;
    _key: string;
  }>;
  description?: string;
  keywords: Array<string>;
  openGraphImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  privacyPolicy: BlockContentSection;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | CarouselSection
  | BlockContentSection
  | ImageSection
  | ResponsiveImage
  | Page
  | Settings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/schemas/pages/page.queries.ts
// Variable: pageQuery
// Query: *[_type == "page" && slug.current == $slug][0]{  _id,  _type,  _createdAt,  _updatedAt,  _rev,  title,  slug,  metadata{    metaTitle,    metaDescription,    keywords,    ogImage{      ...,      asset->    },    noIndex  },  sections[]{    _key,    _type,    title,    description,    text,    images[]{      ...,      asset->,      alt,      aspectRatio    },    body[]{      ...,      _type == 'image' => {        ...,        asset->      }    },    image{      ...,      image{        ...,        asset->      },      aspectRatio    },    backgroundImage{      ...,      asset->    },    layout,    fullWidth,    phone,    address,    email,    showCtaCard,    ctaText,    instagramUrl,    ctaPosition  }}
export type PageQueryResult = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  metadata: {
    metaTitle: string | null;
    metaDescription: string | null;
    keywords: Array<string> | null;
    ogImage: {
      asset: {
        _id: string;
        _type: 'sanity.imageAsset';
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    } | null;
    noIndex: boolean | null;
  } | null;
  sections: Array<
    | {
        _key: string;
        _type: 'carouselSection';
        title: string | null;
        description: null;
        text: null;
        images: Array<{
          _key: string;
          _type: 'responsiveImage';
          image: {
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt: string;
            _type: 'image';
          };
          aspectRatio: '1/1' | '13/5' | '3/2' | '3/4' | '4/3' | '9/16';
          asset: null;
          alt: null;
        }>;
        body: null;
        image: null;
        backgroundImage: null;
        layout: null;
        fullWidth: null;
        phone: null;
        address: null;
        email: null;
        showCtaCard: boolean | null;
        ctaText: string | null;
        instagramUrl: string | null;
        ctaPosition: number | null;
      }
    | {
        _key: string;
        _type: 'imageSection';
        title: string;
        description: null;
        text: null;
        images: null;
        body: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: 'span';
                _key: string;
              }>;
              style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
              listItem?: 'bullet';
              markDefs?: Array<{
                href?: string;
                _type: 'link';
                _key: string;
              }>;
              level?: number;
              _type: 'block';
              _key: string;
            }
          | {
              asset: {
                _id: string;
                _type: 'sanity.imageAsset';
                _createdAt: string;
                _updatedAt: string;
                _rev: string;
                originalFilename?: string;
                label?: string;
                title?: string;
                description?: string;
                altText?: string;
                sha1hash?: string;
                extension?: string;
                mimeType?: string;
                size?: number;
                assetId?: string;
                uploadId?: string;
                path?: string;
                url?: string;
                metadata?: SanityImageMetadata;
                source?: SanityAssetSourceData;
              } | null;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              alt?: string;
              _type: 'image';
              _key: string;
            }
        >;
        image: {
          _type: 'responsiveImage';
          image: {
            asset: {
              _id: string;
              _type: 'sanity.imageAsset';
              _createdAt: string;
              _updatedAt: string;
              _rev: string;
              originalFilename?: string;
              label?: string;
              title?: string;
              description?: string;
              altText?: string;
              sha1hash?: string;
              extension?: string;
              mimeType?: string;
              size?: number;
              assetId?: string;
              uploadId?: string;
              path?: string;
              url?: string;
              metadata?: SanityImageMetadata;
              source?: SanityAssetSourceData;
            } | null;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt: string;
            _type: 'image';
          };
          aspectRatio: '1/1' | '13/5' | '3/2' | '3/4' | '4/3' | '9/16';
        };
        backgroundImage: null;
        layout: 'left' | 'right';
        fullWidth: boolean | null;
        phone: null;
        address: null;
        email: null;
        showCtaCard: null;
        ctaText: null;
        instagramUrl: null;
        ctaPosition: null;
      }
  >;
} | null;
// Variable: allPagesQuery
// Query: *[_type == "page"]{  _id,  title,  slug}
export type AllPagesQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "page" && slug.current == $slug][0]{\n  _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev,\n  title,\n  slug,\n  metadata{\n    metaTitle,\n    metaDescription,\n    keywords,\n    ogImage{\n      ...,\n      asset->\n    },\n    noIndex\n  },\n  sections[]{\n    _key,\n    _type,\n    title,\n    description,\n    text,\n    images[]{\n      ...,\n      asset->,\n      alt,\n      aspectRatio\n    },\n    body[]{\n      ...,\n      _type == \'image\' => {\n        ...,\n        asset->\n      }\n    },\n    image{\n      ...,\n      image{\n        ...,\n        asset->\n      },\n      aspectRatio\n    },\n    backgroundImage{\n      ...,\n      asset->\n    },\n    layout,\n    fullWidth,\n    phone,\n    address,\n    email,\n    showCtaCard,\n    ctaText,\n    instagramUrl,\n    ctaPosition\n  }\n}': PageQueryResult;
    '*[_type == "page"]{\n  _id,\n  title,\n  slug\n}': AllPagesQueryResult;
  }
}
